site_name: pacsanini
repo_url: https://github.com/Therapixel/pacsanini
repo_name: 'GitHub'

markdown_extensions:
    - toc:
        permalink: "#"
    - mkdocs-click
    - attr_list
    - pymdownx.tabbed
    - pymdownx.snippets
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 'index.md'
  - 'User Guide':
    - Overview: 'user_guide/index.md'
    - Installation: 'user_guide/installation.md'
    - Configuration: 'user_guide/configuration.md'
    - Collection: 'user_guide/collection.md'
    - Tutorials:
      - 'Finding DICOM': 'user_guide/tutorials/finding.md'
      - 'Moving DICOM': 'user_guide/tutorials/moving.md'
      - 'Parsing DICOM': 'user_guide/tutorials/parsing.md'
      - 'Storing DICOM': 'user_guide/tutorials/storescp.md'
      - 'Using databases': 'user_guide/tutorials/database.md'
      - 'Running a pipeline': 'user_guide/tutorials/pipeline.md'
  - 'API Reference':
    - Overview: 'api_reference/index.md'
    - cli: 'api_reference/cli.md'
    - config: 'api_reference/config.md'
    - convert: 'api_reference/convert.md'
    - db: 'api_reference/db.md'
    - errors: 'api_reference/errors.md'
    - io: 'api_reference/io.md'
    - models: 'api_reference/models.md'
    - net: 'api_reference/net.md'
    - parse: 'api_reference/parse.md'
    - pipeline: 'api_reference/pipeline.md'
    - utils: 'api_reference/utils.md'
  - 'CLI Reference': 'cli_reference/index.md'
  - About:
    - Contributing: 'about/contributing.md'
    - 'Developer Certificate of Origin': 'about/dco.md'
    - 'Code of Conduct': 'about/code_of_conduct.md'
    - License: 'about/license.md'

plugins:
- search:
    lang: en
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
          show_root_heading: true
        selection:
          docstring_style: numpy
        setup_commands:
            - import sys
            - sys.path.append("./src")

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
